// NO MODIFICAR ABSOLUTAMENTE NADA DE AQUI
let handler = async (m, { conn, text }) => {
    let name = m.fromMe ? conn.user : conn.contacts[m.sender]

  conn.reply(m.chat, `
*❗❗EL DESCONOCIMIENTO DE LO QUE AQUI SE MENCIONA NO EXIME AL PROPIETARIO DEL BOT O USUARIO DEL BOT DE LA SANCIONES QUE SE PUEDAN DERIVAR❗❗*

*⚠️ TERMINOS DE PRIVACIDAD*

_1.- LA INFORMACION QUE RECIBA EL BOT NO SE COMPARTE CON NINGUN TERCERO NI CON NADIE_
_2.- LAS IMAGENES/VIDEOS/STICKER/AUDIOS/ETC NO SON COMPARTIDOS CON NADIE_
_3.- SU NUMERO DE TELEFONO NO ES COMPARTIDO CON ABSOLUTAMENTE NADIE_
_4.- DATOS DE TARJETAS, UBICACIONES, DIRRECCIONES, ETC SON ELIMINADOS INMEDIATAMENTE Y NO SE COMPARTEN CON ABSOLUTAMENTE NADIE_
_5.- TODAS LAS CONVERSACIONES SON ELIMINADAS CADA DETERMINADO TIEMPO Y NO SE HACE BACKUP (NO SE GUARDA) DE NINGUN TIPO DE INFORMACION/CONVERSACION_

*⚠️ TERMINOS DE USO*

_1.- NO NOS HACEMOS RESPONSABLES DE UN MAL USO QUE SE LE PUEDA DAR AL BOT_
_2.- NO NOS HACEMOS REPONSABLES DE LA IGNORANCIA Y/O DESCONOCIMIENTO DEL TEMA_
_3.- EL BOT NO ESTA ACTIVO LAS 24 HORAS Y NO SIEMPRE ESTARA ACTIVO_
_4.- LA "EMPRESA" NO SE HACE RESPONSABLE DEL USO DE UN SUB BOT O BOT NO OFICIAL, YA QUE SON PERSONAS (TERCEROS) Y NO TENEMOS CONTROL SOBRE ELL@S_
_5.- NO NOS HACEMOS RESPONSABLES DE LOS NÚMEROS QUE SE PUEDAN IR A SOPORTE POR EL USO DEL BOT, ES ACONSEJABLE SIEMPRE USAR NÚMEROS VIRTUALES PARA USOS DE BOTS_
_6.- LOS AUDIOS/NOTAS DE VOZ/IMAGENES/VIDEOS O CUALQUIER OTRO ARCHIVO MULTIMEDIA QUE SEAN DE PROPIEDAD DE THE SHADOW BROKERS - BOT SON ÚNICAMENTE Y EXCLUSIVAMENTE DE ESTE BOT, SI SE DETECTA A OTRO BOT CON ALGUNO O ALGUNOS DE LOS ARCHIVOS MULTIMEDIA ANTES MENCIONADO SE TOMARÁN CARTAS EN EL ASUNTO._

*🔰 MENSAJE DEL NUMERO DEL BOT?*

_- SI EN ELAGUN MOMENTO RECIBE UN MENSAJE DEL NUMERO DEL BOT Y NO ES UN COMANDO POSIBLEMENTE SEA EL CREADOR DEL BOT O EL PROPIETARIO DEL MOMENTO, ESTE ES UN PERSONA REAL POR LO QUE SE LE PIDE QUE NO LE FALTE EL RESPETO_

*⁉️ TE QUEDARON DUDAS?*

_- SI TODAVIA TIENES DUDAS SOBRE ALGO REFERENTE AL BOT CONTACTAME A MI NUMERO PERSONAL AL CUAL ESTARE RESPONDIENDO LO ANTES POSIBLE PARA BRINDARTE UNA SOLUCION Y/O HACERME RESPONSABLE_ 
> wa.me/5219996125657
> Bruno Sobrino 

→ *SOLO CONTACTAR POR TEMAS SERIOS, PARA PREGUNTAS DEL BOT MAS GENERALES CONTÁCTAME AL PRIVADO CON EL COMANDO #owner (AL NUMERO wa.me/48699526313)*

*_∆ THE SHADOW BROKERS - BOT ∆_*
`.trim(), m)
    let mentionedJid = [m.sender]
}
    
handler.customPrefix = /términos y condiciones y privacidad|terminosycondicionesyprivacidad|terminosycondiciones|terminos y condiciones y privacidad|terminos y condiciones|terminos y condiciones|terminos de uso|Terminos de uso|Terminó se uso|términos de uso|Términos de uso|Términos y condiciones/i
handler.command = new RegExp

module.exports = handler 